## Swagger

### Get Swagger UI

GET  BASE_URL:HTTP_PORT

### Get Raw JSON

GET  BASE_URL:HTTP_PORT/api-docs/openapi.json

## User

### User Options

OPTIONS BASE_URL:HTTP_PORT/user
Content-Type: application/json
Authorization: Bearer Token

### Create user

POST BASE_URL:HTTP_PORT/user
Content-Type: application/json

{
  "name": "Victor Navarro",
  "email": "bush1d3v@gmail.com",
  "password": "12345678%"
}

### Login user

POST BASE_URL:HTTP_PORT/user/login
Content-Type: application/json

{
  "email": "bush1d3v@gmail.com",
  "password": "12345678%"
}

### User detail

GET BASE_URL:HTTP_PORT/user/:id
Content-Type: application/json
Authorization: Bearer Token

### User list

GET BASE_URL:HTTP_PORT/user
Content-Type: application/json
Authorization: Bearer Token

### Update user

PATCH BASE_URL:HTTP_PORT/user/:id
Content-Type: application/json
Authorization: Bearer Token

{
  "email": "bush1d3v2@gmail.com",
  "password": "12345678%"
}

### Delete user

DELETE BASE_URL:HTTP_PORT/user/:id
Content-Type: application/json
Authorization: Bearer Token

{
  "password": "12345678%"
}
