## User

### Create user

POST http://localhost:8080/user
Content-Type: application/json

### Login user

POST http://localhost:8080/user/login
Content-Type: application/json

{
  "name": "Victor Navarro",
  "email": "bush1d3v@gmail.com",
  "password": "12345678%"
}

### User detail

GET http://localhost:8080/user/:id
Content-Type: application/json
Authorization: Bearer Token


### Update user

PATCH http://localhost:8080/user/:id
Content-Type: application/json
Authorization: Bearer Token

{
  "email": "bush1d3v2@gmail.com"
}

### Delete user

DELETE http://localhost:8080/user/:id
Content-Type: application/json
Authorization: Bearer Token

{
  "password": "12345678%"
}