name: Navarro Blog API Build CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    # - name: Run tests
    #   run: cargo test -- --test-threads=1
